config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]

  resources :comments, only: [:create, :destroy]

  get 'oimos/top' => 'oimos#top'
  
  get 'oimos/shop_new' => 'oimos#shop_new'

  resources :potatos do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :oimos do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # root 'potatos#top'
  root 'oimos#top'

  resources :tags do
    get 'oimos', to: 'oimos#search'
  end

  

  resources :tags do
    get 'potatos', to: 'potatos#search'
  end




end

app/models/potato.rb
class Potato < ApplicationRecord

    mount_uploader :image, ImageUploader

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_potato_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_potato_tag
    end
  end
end

app/controllers/potatos_controller.rb
class PotatosController < ApplicationController

    def index
        @potatos = Potato.all
        @tag_list = Tag.all.sort {|a,b| b.potatos.count <=> a.potatos.count} 
        if params[:search] != nil && params[:search] != ''
        search = params[:search]
        @potatos = Potato.joins(:tags).where("body LIKE ? OR tag_name LIKE ?", "%#{search}%", "%#{search}%")
        else
        @potatos = Potato.all
        end
        if params[:tag_id]
        @potatos = []
        params[:tag_id].each do |key, value|      
            @potatos += Tag.find_by(tag_name: key).potatos if value == "1"
        end
        @potatos.uniq!
        end
    end

    def new
      @potato = Potato.new
    end

    def create
        potato = current_user.potatos.new(potato_params)           
        tag_list = params[:potato][:tag_name].split(',')

        if potato.save!
           potato.save_tag(tag_list)
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
      @potato = Potato.find(params[:id])
      @potato_tags = @potato.tags
      @comments = @potato.comments
      @comment = Comment.new
    end

    def edit
        @potato = Potato.find(params[:id])
        @tag_list=@potato.tags.pluck(:tag_name).join(nil)
    end

    def update

        potato = Potato.find(params[:id])
        tag_list = params[:potato][:tag_name].split(nil)
        if potato.update(potato_params)
            old_relations = TagMap.where(potato_id: potato.id)
            old_relations.each do |relation|
              relation.delete
        end

          potato.save_tag(tag_list)
          redirect_to potato_path(potato.id), notice:'投稿完了しました:)'
        else
          redirect_to :action => "edit"
        end
    end

    def destroy
        potato = Potato.find(params[:id])
        potato.destroy
        redirect_to action: :index
    end


    private
      def potato_params
        params.require(:potato).permit(:recipe_name, :recipe_abput, :image)
      end

end

app/helpers/potato_helper.rb
module PotatoHelper
end

app/views/potatos/edit.html.erb
<div class="edit">
    <%= link_to 'トップページ', oimos_top_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= link_to 'shop投稿一覧', oimos_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= link_to 'recipe投稿一覧', potatos_path, class:"btn btn-malformation btn-malformation--pastel" %>

    <%= link_to "shop新規投稿ページ", oimos_shop_new_path, class:"btn btn-malformation btn-malformation--pastel" %>

    <%= link_to "recipe新規投稿ページ", new_potato_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= form_for @potato do |f| %>
    <div class="form">
        <%= f.label :body %>
        <%= f.text_field :recipe_name, :size => 40 %> 

        <div class="field">
            <%= f.label"タグ (スペースで区切ると複数タグ登録できます)" %>
            <%= f.text_field :tag_name, value: @tag_list,class:"form-control"%>
        </div>

        <%= f.submit "編集する" %>
    </div>

    <% end %>
</div>

app/views/potatos/index.html.erb
<div class="all">
    <h1>おいも RECIPE投稿一覧</h1>

  <div class="link">
        <%= link_to 'トップページ', oimos_top_path, class:"btn btn-malformation btn-malformation--pastel" %>
        <%= link_to 'shop投稿一覧', oimos_path, class:"btn btn-malformation btn-malformation--pastel" %>

        <%= link_to "shop新規投稿ページ", oimos_shop_new_path, class:"btn btn-malformation btn-malformation--pastel" %>

        <%= link_to "recipe新規投稿ページ", new_potato_path, class:"btn btn-malformation btn-malformation--pastel" %>
  </div>

    <div class="potatos-containor">
        <% @potatos.each do |t| %>
            <div class="potato">

                <%= image_tag t.image_url, size: "250x200" if t.image? %>

                <%= t.recipe_name %>
                <%= t.recipe_about %>

                <%= link_to t.user.name, user_path(t.user.id) %> 
                <%= t.user.email %>

                <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                    <%= link_to potato_like_path(id: t.id, potato_id: t.id), method: :delete do %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                        <p>いいねを取り消す</p><%= t.likes.count %>
                    <% end %>
                <% else %>
                    <%= link_to potato_likes_path(id: t.id, potato_id: t.id), method: :post do %>
                        <i class="far fa-heart"></i><%= t.likes.count %>
                        <p>いいね</p><%= t.likes.count %>
                    <% end %>
                <% end %>
                <% else %>
                <i class="far fa-heart"></i><%= t.likes.count %>
                <p>いいねの数 = </p><%= t.likes.count %>
                <% end %>

                <%= link_to "詳細へ", potato_path(t.id) %>
                <%= link_to "編集する", edit_potato_path(t.id) %>
                <%= button_to "削除する", potato_path(t.id), method: :delete %>
            </div>
        <% end %>
    </div>

</div>

app/views/potatos/new.html.erb
<div class="recipenew">
  <h1>新規のおいも<h1>
  <h3>RECIPE<h3>
 <div class="link">
    <%= link_to "トップページ", oimos_top_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= link_to 'shop投稿一覧', oimos_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= link_to 'recipe投稿一覧', potatos_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= link_to "shop新規投稿ページ", oimos_shop_new_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= form_for @potato do |f| %>
 </div>

    <div class="form">

      <div class="name">
        <%= f.label :recipe_name %>
        <%= f.text_field :recipe_name, :size => 30 %>
      </div>
    
      <div class="about">
        <%= f.label :recipe_about  %>
        <%= f.text_area :recipe_about, :size => "30x2" %>
      </div>
    
      <div class="recipeimage">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>


      <%= form_with(model: @potato, url: potatos_path, local: true) do |f| %>
        <p>半角スペースを入力することで複数のタグを付けることができます。</p>
        <%= f.text_field :tag_name, placeholder: "Ruby Python Java" %>
        <%= f.submit "投稿する" %>
      <% end %>
      
      <% end %>
      </div>
      <%= link_to "一覧に戻る", potatos_path %>
     
</div>

app/views/potatos/show.html.erb
<div class="detail">
  <h1>おいも</h1>
  <h3>おいも詳細</h3>
  <div class="potato">
    <p><%= @potato.recipe_name %></p>
    <p><%= @potato.recipe_about %></p>
    <p><%= @potato.created_at %></p>
    <% if user_signed_in? %>
    <% if current_user.already_liked?(@potato) %>
      <%= link_to potato_like_path(@potato), method: :delete do %>
        <i class="far fa-heart"></i><%= @potato.likes.count %>
        <p>いいねを取り消す</p><%= @potato.likes.count %>
      <% end %>
    <% else %>
      <%= link_to potato_likes_path(@potato), method: :post do %>
        <p>いいね</p><%= @potato.likes.count %>
      <% end %>
    <% end %>
  <% else %>
    <i class="far fa-heart"></i><%= @potato.likes.count %>
    <p>いいねの数 = </p><%= @potato.likes.count %>
  <% end %>
  <%= link_to "編集する", edit_potato_path(@potato.id) %>
  </div>

  <h2>いいねしたユーザー</h2>
  <% @potato.liked_users.each do |user| %>
  <li><%= user.email %></li>
  <% end %>  
  </div>

  <div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
      <div>
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
      </div>
        <br>
      <% if user_signed_in? && current_user.id == c.user_id %>
        <%= button_to "削除する", potato_comments_path(c.id), method: :delete %>
    <% end %>
    <% end %>

    <% if user_signed_in? %>
      <%= form_with(model: [@potato, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%= link_to "おいも一覧に戻る", potatos_path %>
  <%= link_to "編集する", edit_potato_path(@potato.id) %>

  <% @potato_tags.each do |tag| %>
    <% if tag.potatos.count > 0 %>
    <i class="fas fa-paperclip"></i>
      <%= link_to tag.tag_name, tag_potatos_path(tag_id: tag.id) %>
      <%= "(#{tag.potatos.count})" %>
    <% end %>
  <% end %>
</div>