config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]

  resources :comments, only: [:create, :destroy]

  get 'oimos/top' => 'oimos#top'
  
  get 'oimos/shop_new' => 'oimos#shop_new'

  resources :potatos do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :oimos do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # root 'potatos#top'
  root 'oimos#top'

  resources :tags do
    get 'oimos', to: 'oimos#search'
  end

  

  resources :tags do
    get 'potatos', to: 'potatos#search'
  end




end

app/models/oimo.rb
class Oimo < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_oimo_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_oimo_tag
    end
  end

end

app/controllers/oimos_controller.rb
class OimosController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

    def index
        @oimos = Oimo.all
        @tag_list = Tag.all.sort {|a,b| b.oimos.count <=> a.oimos.count} 
    if params[:search] != nil && params[:search] != ''
      search = params[:search]
      @oimos = Oimo.joins(:tags).where("body LIKE ? OR tag_name LIKE ?", "%#{search}%", "%#{search}%")
    else
      @oimos = Oimo.all
    end
    if params[:tag_id]
      @oimos = []
      params[:tag_id].each do |key, value|      
        @oimos += Tag.find_by(tag_name: key).oimos if value == "1"
      end
      @oimos.uniq!
    end
    end

    def shop_new
        @oimo = Oimo.new
        
      end

      def recipe_new
        @oimo = Oimo.new
        @oimo = current_user.oimos.new
      end

      def create
        oimo = current_user.oimos.new(oimo_params)           
        tag_list = params[:oimo][:tag_name].split(nil)

        if oimo.save!
           oimo.save_tag(tag_list)
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @oimo = Oimo.find(params[:id])
        @oimo_tags = @oimo.tags
        @comments = @oimo.comments
        @comment = Comment.new
      end


      def edit
        @oimo = Oimo.find(params[:id])
        @tag_list=@oimo.tags.pluck(:tag_name).join(nil)
      end

      def update

        oimo = Oimo.find(params[:id])
        tag_list = params[:oimo][:tag_name].split(nil)
          if oimo.update(oimo_params)
            old_relations = TagMap.where(oimo_id: oimo.id)
            old_relations.each do |relation|
              relation.delete
          end

          oimo.save_tag(tag_list)
          redirect_to oimo_path(oimo.id), notice:'投稿完了しました:)'
        else
          redirect_to :action => "edit"
        end
      end

      def destroy
        oimo = Oimo.find(params[:id])
        oimo.destroy
        redirect_to action: :index
      end

      def top
        if params[:search] != nil && params[:search] != ''
          search = params[:search]
          @tag_list = Tag.where("tag_name LIKE ?", "%#{search}%")
        else
          @tag_list = Tag.all
        end
      end

      def shop
        @shop=Oimo.where(shop_or_recipe:'お店')
      end

      def recipe
        @recipe=Oimo.where(shop_or_recipe:'料理')
      end

      def search
        @tag_list = Tag.all               
        @tag = Tag.find(params[:tag_id])  
        @oimos = @tag.oimos.all           
      end  


      private
      def oimo_params
        params.require(:oimo).permit(:shop_or_recipe, :shop_name, :adresses, :shop_about, :image)
      end

end

app/helpers/oimos_helper.rb
module OimosHelper
end

app/views/oimos/edit.html.erb
<div class="edit">
 <%= link_to 'トップページ', oimos_top_path, class:"btn btn-malformation btn-malformation--pastel" %>
 <%= link_to 'shop投稿一覧', oimos_path, class:"btn btn-malformation btn-malformation--pastel" %>
 <%= link_to 'recipe投稿一覧', potatos_path, class:"btn btn-malformation btn-malformation--pastel" %>

 <%= link_to "shop新規投稿ページ", oimos_shop_new_path, class:"btn btn-malformation btn-malformation--pastel" %>

 <%= link_to "recipe新規投稿ページ", new_potato_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= form_for @oimo do |f| %>
    <div class="form">
        <%= f.label :shop_name %>
        <%= f.text_field :shop_name, :size => 40%> 

        <div class="field">
            <%= f.label"タグ (スペースで区切ると複数タグ登録できます)" %>
            <%= f.text_field :tag_name, value: @tag_list,class:"form-control"%>
        </div>

        <%= f.submit "編集する" %>
    </div>

    <% end %>
</div>

app/views/oimos/index.html.erb
<div class="all">  
  <h1>おいも</h1>
  <h3>おいも一覧</h3>
    <div class="link">
      <%= link_to 'トップページ', oimos_top_path, class:"btn btn-malformation btn-malformation--pastel" %>
      <%= link_to 'recipe投稿一覧', potatos_path, class:"btn btn-malformation btn-malformation--pastel" %>

      <%= link_to "shop新規投稿ページ", oimos_shop_new_path, class:"btn btn-malformation btn-malformation--pastel" %>

      <%= link_to "recipe新規投稿ページ", new_potato_path, class:"btn btn-malformation btn-malformation--pastel" %>
    </div>



  

   <% if user_signed_in? %>
    <%= link_to "マイページへ", user_path(current_user.id) %>
   <% end %>
  <div class="oimos-container">
    <% @oimos.each do |t| %>
      <div class="oimo">

        <%= image_tag t.image_url, size: "250x200" if t.image? %>

        <%= t.shop_name %>
        <%= t.adresses %>
        <%= t.shop_about %>

        <%= link_to t.user.name, user_path(t.user.id) %> 
        <%= t.user.email %>

        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to oimo_like_path(id: t.id, oimo_id: t.id), method: :delete do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                  <p>いいねを取り消す</p><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to oimo_likes_path(id: t.id, oimo_id: t.id), method: :post do %>
                  <i class="far fa-heart"></i><%= t.likes.count %>
                  <p>いいね</p><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
          <p>いいねの数 = </p><%= t.likes.count %>
        <% end %>

        <%= link_to "詳細へ", oimo_path(t.id) %>
        <%= link_to "編集する", edit_oimo_path(t.id) %>
        <%= button_to "削除する", oimo_path(t.id), method: :delete %>
      </div>
    <% end %>
  </div>
  <div class="tag">
    <h3>タグ検索のチェックボックス</h3>
    <%= form_tag({controller:"oimos",action:"index"}, method: :get) do %>
      <% Tag.all.each do |t| %>
        <div class = 'check_box'> 
          <%= check_box :tag_id, t.tag_name %><%= t.tag_name %><%= "(#{t.oimos.count})" %>
        </div>
      <% end %>
      <%= submit_tag '検索' %>
    <% end %>

    <h3>タグリスト</h3>
    <% @tag_list.each do |list| %>
      #<%= link_to list.tag_name, tag_oimos_path(tag_id: list.id) %>
      <%= "(#{list.oimos.count})" %>
    <% end %>
  </div>

  <% @oimos.each do |oimo| %> 

        #<%= link_to tag.tag_name, tag_oimos_path(tag_id: tag.id) %>
  <% end %>
</div>

app/views/oimos/recipe.html.erb
<h1>おいも レシピ投稿一覧</h1>

<% @recipe.each do |t| %>
    <div class="oimo">

      <%= image_tag t.image_url, size: "250x200" if t.image? %>

      <%= t.shop_name %>
      <%= t.adresses %>
      <%= t.shop_about %>

      <%= link_to t.user.name, user_path(t.user.id) %> 
      <%= t.user.email %>

      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to oimo_like_path(id: t.id, oimo_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
              <p>いいねを取り消す</p><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to oimo_likes_path(id: t.id, oimo_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
              <p>いいね</p><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

    <%= link_to "詳細へ", oimo_path(t.id) %>
    <%= link_to "編集する", edit_oimo_path(t.id) %>
    <%= button_to "削除する", oimo_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/oimos/recipe_new.html.erb
<%= form_for @potato do |f| %>

 <div class="field">
    <%= f.label :recipe_name %>
    <%= f.text_field :recipe_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :recipe_about  %>
    <%= f.text_area :recipe_about, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  
<% end %>

app/views/oimos/search.html.erb
<h3>タグリスト</h3>
<% @tag_list.each do |list| %>
  <%= list.tag_name %>
  <%= "(#{list.oimos.count})" %>
<% end %>
<br>
<%= "#{@tag.tag_name}" %>
<br>
<% @oimos.each do |oimo| %>
  <%= link_to oimo.content, oimo %>
<% end %>

app/views/oimos/shop.html.erb
<h1>おいも お店投稿一覧</h1>

<%= link_to 'お店投稿一覧', oimos_path, class:"btn btn-malformation btn-malformation--pastel" %>
<%= link_to 'レシピ投稿一覧', potatos_path, class:"btn btn-malformation btn-malformation--pastel" %>

<%= link_to "shop新規投稿ページ", oimos_shop_new_path, class:"btn btn-malformation btn-malformation--pastel" %>

<%= link_to "recipe新規投稿ページ", new_potato_path, class:"btn btn-malformation btn-malformation--pastel" %>

<% @shop.each do |t| %>
    <div class="oimo">

      <%= image_tag t.image_url, size: "250x200" if t.image? %>

      <%= t.shop_name %>
      <%= t.adresses %>
      <%= t.shop_about %>

      <%= link_to t.user.name, user_path(t.user.id) %> 
      <%= t.user.email %>

      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to oimo_like_path(id: t.id, oimo_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
              <p>いいねを取り消す</p>
          <% end %>
      <% else %>
          <%= link_to oimo_likes_path(id: t.id, oimo_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

    <%= link_to "詳細へ", oimo_path(t.id) %>
    <%= link_to "編集する", edit_oimo_path(t.id) %>
    <%= button_to "削除する", oimo_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/oimos/shop_new.html.erb
<div class="shopnew">
  <h1>新規のおいも</h1>
  <h3>SHOP</h3>

 <div class="link">
    <%= link_to "トップページ", oimos_top_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= link_to 'shop投稿一覧', oimos_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= link_to 'recipe投稿一覧', potatos_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= link_to "recipe新規投稿ページ", new_potato_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= form_with(model: @oimo, url: oimos_path, local: true) do |f| %>
 </div>

    <div class="form">

      <div class="field">
        <%= f.label :shop_or_recipe  %>
        <%= f.select :shop_or_recipe, 
        [["お店", "お店"], 
        ["料理", "料理"], 
        ["その他", "その他"]], include_blank: "選択して下さい" %>
      </div>

      <div class="name">
        <%= f.label :shop_name %>
        <%= f.text_field :shop_name, :size => 30 %>
      </div>

      <div class="adress">
        <%= f.label :adresses  %>
        <%= f.number_field :adresses, :size => 10 %>
      </div>

      <div class="about">
        <%= f.label :shop_about  %>
        <%= f.text_area :shop_about, :size => "30x2" %>
      </div>

    

      <div class="shopimage">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>

      <p>半角スペースを入力することで複数のタグを付けることができます。</p>
      <%= f.text_field :tag_name, placeholder: "Ruby Python Java" %>
      <%= f.submit "投稿する" %>
      <% end %>
    </div>

  <%= link_to "一覧に戻る", oimos_path %>
</div>

    

app/views/oimos/show.html.erb
<div class="detail">
  <h1>おいも</h1>
  <h3>おいも詳細</h3>
  <div class="oimo">
    <p><%= @oimo.shop_name %></p>
    <p><%= @oimo.adresses %></p>
    <p><%= @oimo.shop_about %></p>
    <p><%= @oimo.created_at %></p>
    <% if user_signed_in? %>
    <% if current_user.already_liked?(@oimo) %>
      <%= link_to oimo_like_path(@oimo), method: :delete do %>
        <i class="far fa-heart"></i><%= @oimo.likes.count %>
        <p>いいねを取り消す</p><%= @oimo.likes.count %>
      <% end %>
    <% else %>
      <%= link_to oimo_likes_path(@oimo), method: :post do %>
        <p>いいね</p><%= @oimo.likes.count %>
      <% end %>
    <% end %>
  <% else %>
    <i class="far fa-heart"></i><%= @oimo.likes.count %>
    <p>いいねの数 = </p><%= @oimo.likes.count %>
  <% end %>
  <%= link_to "編集する", edit_oimo_path(@oimo.id) %>
  </div>

  <h2>いいねしたユーザー</h2>
  <% @oimo.liked_users.each do |user| %>
  <li><%= user.email %></li>
  <% end %>  
  </div>

  <div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
      <div>
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
      </div>
        <br>
      <% if user_signed_in? && current_user.id == c.user_id %>
        <%= button_to "削除する", oimo_comments_path(c.id), method: :delete %>
    <% end %>
    <% end %>

    <% if user_signed_in? %>
      <%= form_with(model: [@oimo, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%= link_to "おいも一覧に戻る", oimos_path %>
  <%= link_to "編集する", edit_oimo_path(@oimo.id) %>

  <% @oimo_tags.each do |tag| %>
    <% if tag.oimos.count > 0 %>
    <i class="fas fa-paperclip"></i>
      <%= link_to tag.tag_name, tag_oimos_path(tag_id: tag.id) %>
      <%= "(#{tag.oimos.count})" %>
    <% end %>
  <% end %>
</div>

app/views/oimos/top.html.erb
<div class="all">  
  <div class = "link" >
    <%= link_to 'shop投稿一覧', oimos_path, class:"btn btn-malformation btn-malformation--pastel" %>
    <%= link_to 'recipe投稿一覧', potatos_path, class:"btn btn-malformation btn-malformation--pastel" %>

    <%= link_to "shop新規投稿ページ", oimos_shop_new_path, class:"btn btn-malformation btn-malformation--pastel" %>

    <%= link_to "recipe新規投稿ページ", new_potato_path, class:"btn btn-malformation btn-malformation--pastel" %>

  </div>

  <h3>タグを検索</h3>
  <%= form_tag({controller:"oimos",action:"top"}, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索する'  %>
  <% end %>
  <br>

  <h3>タグ一覧</h3>
  <% @tag_list.each do |list| %>
    <div class = 'tag一覧' >
    <i class="fas fa-paperclip"></i>
      <%= "(#{list.oimos.count})" %>
    </div>
  <% end %>

  <div class="silk">
    <div class="black">
    </div>
    <div class="white">
    </div>
    <%= image_tag 'silksweet.jpg', class: 'silksweet' %><br>
    <div class="silktitle">
      <h3>シルクスイート</h3>
    </div>
    <div class="silkexplain">
      <p>新しい新種でありますが、他の新種に比べ10分の1程度のため、
      「幻のさつまいも」と評されることもあります。
      外観は紡錘形で、“ザ・さつまいも”のようなフィルム。
      寝かせた時間によって、ホクホク食感とねっとり食感を楽しめる面白い新種です。</p>
    </div>
  </div><br>
  

  <div class="annnou">
    <div class="black">
    </div>
    <div class="white">
    </div>
    <%= image_tag 'annnouimo.jpg', class: 'annnouimo' %><br>
    <div class="annnoutitle">
      <h3>安納芋</h3>
    </div>
    <div class="annnouexplain">
      <p>水分が多く、ねっとりした粘着性を最大限に引き出せ、焼き芋にした時、
      密が溢れるほどのねっとりクリーミーな食感になります。
      生の状態でも糖度が16度程度、時間をかけて焼くことで糖度40度近くまでなるものもある、
      甘さが売りのおいもです！！</p>
    </div>
  </div><br>

  <div class="beni">
    <div class="black">
    </div>
    <div class="white">
    </div>
    <%= image_tag 'beniharuka.jpg', class: 'beniharuka' %><br>
    <div class="benititle">
      <h3>紅はるか</h3>
    </div>
    <div class="beniexplain">
      <p>他のおいもより「はるかに」美味しいという事で名付けられたほど、
      芳醇な香りと高糖度で、スイーツ並みの甘味が特徴です。
      しっとりなめらかな食感と豊富なビタミン・食物繊維で大人気！
      ねっとり焼き芋が好きな方におすすめ！！</p>
    </div>  
  </div><br>
</div>  